/**
 * 
 */
package com.qterp;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.qterp.Order;
import com.qterp.OrderRepository;

/**
 * @author Think
 *
 */

@Controller // This means that this class is a Controller
@RequestMapping(path = "/order") // This means URL's start with /demo (after
									// Application path)
public class OrderController {
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private OrderRepository orderRepository;

	@GetMapping(path = "/add") // Map ONLY GET Requests
	public @ResponseBody String addNewOrder(@RequestParam String customer_name, @RequestParam String customer_address,
			@RequestParam String customer_tel) {
		// @ResponseBody means the returned String is the response, not a view
		// name
		// @RequestParam means it is a parameter from the GET or POST request

		Order order = new Order();
		order.setCustomer_name(customer_name);
		order.setCustomer_address(customer_address);
		order.setCustomer_tel(customer_tel);
		orderRepository.save(order);
		return "Saved";
	}

	@GetMapping(path = "/all")
	public @ResponseBody Iterable<Order> getAllOrder() {
		// This returns a JSON or XML with the users
		return orderRepository.findAll();
	}

}
